### ISSUE TITLE
Who is frank?

### ISSUE THREAD

**Issue by tgoodlet** [tgoodlet/tractor#64]
Thanks to @parity3 for finding this.

The first example in the [actor-spawning-and-causality](https://github.com/tgoodlet/tractor#actor-spawning-and-causality) refers to a `frank` actor that isn't introduced until the 2nd code example later in that section. The first subactor is actually `teacher`..

**Comment by parity3** [comment]
This solves the frank problem. (Did you want me to close?)

**Comment by tgoodlet** [comment]
@parity3 merging #67 will close this automatically.
